name: First Workflow

on: workflow_dispatch

jobs:
  firs-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: |
          echo "Hello!"
          echo $(free -h)
          echo $(cat /proc/loadavg)
          
      - name: Pring hoodby
        run: echo "BYE!"
